### ISSUE TITLE
Regarding time complexity and space complexity

### ISSUE THREAD

**Issue by ex172000** [ItoSchum/myLeetCode#1]
Hi Yitao,

Please include TC/SC analysis of your code. Please improve:
1. Two-sum to linear time complexity O(N)
2. I think to make a number to a string is very slow, and also it costs space, is there any better way?
3. Is appending a string with `+` a time-efficient way in Python? (disclaimer: I don't know myself, it is usually not efficient in Java and many other languages because the new string has to be re-created. If it is the most efficient one, please prove it.)
4. Is `in` a good way to find something in a list? What is the time complexity for this operation in `26`
5. Is there a new way to do `27`, without creating a new list? It's usually space consuming to do that.
6. There are better ways to do `28`. Your current implementation is O(N) with string reconstruction and comparison, which can be improved. There are fancy algorithms, but try to find something not too complex.
7.  I don't think `remove()` and `add()` are `in-place`. Please do it without creating a new array. 

Please also group the files of a day into a specific folder.
Please also include your LC judge testing result.

**Comment by itoschum** [comment]
I've improved my codes, though as for Q28 the fancy way may not perform as well as my original solution.
